guys = [
    "Adam",
    "Chris S.",
    "Chris T.",
    "Dillan",
    "Dre",
    "Ethan",
    "John",
    "Joey",
    "Ryan",
    "Wes",
]

girls = [
    "Amber",
    "Ashleigh",
    "Brittany",
    "Coleysia",
    "Jacy",
    "Jessica",
    "Kayla",
    "Paige",
    "Shanley",
    "Simone",
]

truth_booth = [
    ("Chris T.", "Shanley", False),
    ("Ethan", "Jessica", False),
    ("John", "Simone", False),
    ("Dillan", "Jessica", False),
    ("Dre", "Ashleigh", False),
    ("Dillan", "Coleysia", True),
    ("Chris T.", "Paige", True),
    ("Ryan", "Kayla", False),
    ("Wes", "Kayla", True),
    ("John", "Jacy", False),
]

mc = [
    (
        [
            ("Adam", "Brittany"),
            ("Chris S.", "Ashleigh"),
            ("Chris T.", "Jessica"),
            ("Dillan", "Coleysia"),
            ("Dre", "Jacy"),
            ("Ethan", "Shanley"),
            ("John", "Simone"),
            ("Joey", "Paige"),
            ("Ryan", "Amber"),
            ("Wes", "Kayla"),
        ],
        2,
    ),
    (
        [
            ("Adam", "Shanley"),
            ("Chris S.", "Simone"),
            ("Chris T.", "Paige"),
            ("Dillan", "Jessica"),
            ("Dre", "Ashleigh"),
            ("Ethan", "Amber"),
            ("John", "Jacy"),
            ("Joey", "Brittany"),
            ("Ryan", "Kayla"),
            ("Wes", "Coleysia"),
        ],
        4,
    ),
    (
        [
            ("Adam", "Brittany"),
            ("Chris S.", "Paige"),
            ("Chris T.", "Simone"),
            ("Dillan", "Coleysia"),
            ("Dre", "Ashleigh"),
            ("Ethan", "Amber"),
            ("John", "Jessica"),
            ("Joey", "Shanley"),
            ("Ryan", "Kayla"),
            ("Wes", "Jacy"),
        ],
        2,
    ),
    (
        [
            ("Adam", "Amber"),
            ("Chris S.", "Paige"),
            ("Chris T.", "Ashleigh"),
            ("Dillan", "Coleysia"),
            ("Dre", "Simone"),
            ("Ethan", "Kayla"),
            ("John", "Shanley"),
            ("Joey", "Jacy"),
            ("Ryan", "Brittany"),
            ("Wes", "Jessica"),
        ],
        2,
    ),
    (
        [
            ("Adam", "Shanley"),
            ("Chris S.", "Simone"),
            ("Chris T.", "Paige"),
            ("Dillan", "Coleysia"),
            ("Dre", "Brittany"),
            ("Ethan", "Amber"),
            ("John", "Jacy"),
            ("Joey", "Jessica"),
            ("Ryan", "Ashleigh"),
            ("Wes", "Kayla"),
        ],
        5,
    ),
    (
        [
            ("Adam", "Ashleigh"),
            ("Chris S.", "Brittany"),
            ("Chris T.", "Paige"),
            ("Dillan", "Coleysia"),
            ("Dre", "Shanley"),
            ("Ethan", "Amber"),
            ("John", "Jacy"),
            ("Joey", "Simone"),
            ("Ryan", "Jessica"),
            ("Wes", "Kayla"),
        ],
        5,
    ),
    (
        [
            ("Adam", "Shanley"),
            ("Chris S.", "Jacy"),
            ("Chris T.", "Paige"),
            ("Dillan", "Coleysia"),
            ("Dre", "Simone"),
            ("Ethan", "Amber"),
            ("John", "Brittany"),
            ("Joey", "Jessica"),
            ("Ryan", "Ashleigh"),
            ("Wes", "Kayla"),
        ],
        7,
    ),
    (
        [
            ("Adam", "Shanley"),
            ("Chris S.", "Ashleigh"),
            ("Chris T.", "Paige"),
            ("Dillan", "Coleysia"),
            ("Dre", "Simone"),
            ("Ethan", "Amber"),
            ("John", "Jacy"),
            ("Joey", "Brittany"),
            ("Ryan", "Jessica"),
            ("Wes", "Kayla"),
        ],
        8,
    ),
    (
        [
            ("Adam", "Shanley"),
            ("Chris S.", "Jacy"),
            ("Chris T.", "Paige"),
            ("Dillan", "Coleysia"),
            ("Dre", "Simone"),
            ("Ethan", "Amber"),
            ("John", "Ashleigh"),
            ("Joey", "Brittany"),
            ("Ryan", "Jessica"),
            ("Wes", "Kayla"),
        ],
        10,
    ),
]
