repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: check-ast
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
- repo: https://github.com/ambv/black
  rev: 22.12.0
  hooks:
  - id: black
    language_version: python3.10
